export const backgroundColors = {
    white: '#ffffff',
    red: '#ffcdd2',
    pink: '#f8bbd0',
    purple: '#e1bee7',
    deepPurple: '#d1c4e9',
    indigo: '#c5cae9',
    blue: '#bbdefb',
    lightBlue: '#b3e5fc',
    cyan: '#b2ebf2',
    teal: '#b2dfdb',
    green: '#c8e6c9',
    lightGreen: '#dcedc8',
    lime: '#f0f4c3',
    yellow: '#fff9c4',
    amber: '#ffecb3',
    orange: '#ffe0b2',
    deepOrange: '#ffccbc',
    brown: '#d7ccc8',
    grey:  '#f5f5f5',
    blueGrey: '#cfd8dc'
}

export const backgroundColorsForSelect = [
    { label: 'White', value: '#ffffff' },
    { label: 'Red', value: '#ffcdd2' },
    { label: 'Pink', value: '#f8bbd0' },
    { label: 'Purple', value: '#e1bee7' },
    { label: 'Deep purple', value: '#d1c4e9' },
    { label: 'Indigo', value: '#c5cae9' },
    { label: 'Blue', value: '#bbdefb' },
    { label: 'Light blue', value: '#b3e5fc' },
    { label: 'Cyan', value: '#b2ebf2' },
    { label: 'Teal', value: '#b2dfdb' },
    { label: 'Green ', value: '#c8e6c9' },
    { label: 'Light green', value: '#dcedc8' },
    { label: 'Lime', value: '#f0f4c3' },
    { label: 'Yellow', value: '#fff9c4' },
    { label: 'Amber', value: '#ffecb3' },
    { label: 'Orange', value: '#ffe0b2' },
    { label: 'Deep orange', value: '#ffccbc' },
    { label: 'Brown', value: '#d7ccc8' },
    { label: 'Gray', value: '#f5f5f5' },
    { label: 'Blue gray', value: '#cfd8dc' }
]